### ISSUE TITLE
count 组件，文档错误

### ISSUE THREAD

**Issue by zaxlct** [meili/minui#11]
代码示例是这样的： `max={{10000}}` 
正确应该是这样的：`max="{{10000}}"`

我是从小程序示例文档里看到的，本来准备发个 PR 顺手给改了，不过没在 minui 仓库里找到在哪改 = =

**Comment by badeng** [comment]
收到，感谢您的反馈，我们会尽快修改过来

**Comment by badeng** [comment]
counter组件的demo示例代码max等属性的规范化已完成，谢谢您的反馈。
