### ISSUE TITLE
popup 组件示例代码里的 'selectComponent' 方法找不到

### ISSUE THREAD

**Issue by zaxlct** [meili/minui#13]
popup 组件的示例代码里
```
 showPopup() {
     let popupComponent = this.selectComponent('.J_Popup')
     popupComponent && popupComponent.show()
 },
```
`selectComponent` 方法不是Component构造器内部使用的方法吗，在 Page 里能使用吗？

正常在 Page 内是不是该用 wx.createSelectorQuery() 方法来选择组件？

**Comment by min-team** [comment]
@zaxlct  selectComponent() 是微信容器支持的 Component 构造器的方法，使用选择器选择组件实例节点，返回匹配到的第一个组件实例对象。和 createSelectorQuery 不是一个方法。具体可详见微信小程序官方文档&自定义组件支持相关文档的内容。

**Comment by min-team** [comment]
@zaxlct 你好，经过验证是可以在page中调用selectComponent方法得到一个组件的实例，对于popup、dialog等组件，通过selectComponent获取组件实例后，可直接调用该组件的show()、hide()方法。

**Comment by zaxlct** [comment]
@min-team 感谢回复，谢谢。
