### ISSUE TITLE
我正在使用wepy，想使用minui，遇到问题。

### ISSUE THREAD

**Issue by jimmyrogue** [meili/minui#15]
项目地址 https://github.com/jimmyrogue/wepy-X-minui/tree/master
首先是配置：
`
{
  "npm": {
    "dest": "dist/packages"
  }
}
`

引用方式 (应用页面为index)

`
usingComponents: {
        "wxc-dialog": "../packages/@minui/wxc-dialog/dist"
      }
`

项目结构
![文件](https://ws3.sinaimg.cn/large/006tNc79gy1flt55os5waj30c40hu3zs.jpg)

遇到的提示
![文件](https://ws3.sinaimg.cn/large/006tNc79gy1flt56831fmj317u0os46z.jpg)

求教

**Comment by zaxlct** [comment]
我来回答这个问题吧，下面是答案。
（PS 我建议还是用 zan-ui 吧，我用 minui 遇到了几个问题，提了 issues 好几天没有回复）

![image](https://user-images.githubusercontent.com/14342431/33226962-1e41057a-d1d4-11e7-8eec-c3e55af02a88.png)


```javascript
usingComponents: {
  'wxc-icon': '/minui/@minui/wxc-icon/_dist/index'
},
```
```

**Comment by zaxlct** [comment]
@jimmyrogue

**Comment by badeng** [comment]
这个是wepy要求关闭es6=>es5导致的，上周五我们已经在跟进这个问题了。

**Comment by min-team** [comment]
@jimmyrogue 之前我们在微信群里沟通就没在这里同步了，由于MinUI部分组件用到了es6代码，目前 Min Cli 工具未对es6代码进行转换，而wepy要求关闭 es6 => es5，近期Min Cli 会增加一项es6 => es5 转换选项将其等类似修复掉。

**Comment by jimmyrogue** [comment]
@min-team 是的，编译这边已经不报错了，但是按照demo里的方法调用提示无此方法
```
let dialogComponent = this.selectComponent('.wxc-dialog')
dialogComponent && dialogComponent.show();
```

```
this.selectComponent is not a function;
```

**Comment by min-team** [comment]
this.selectComponent 在Component 构造器里调用的么

**Comment by jimmyrogue** [comment]
@min-team 不是，就是在一个page里，比方说我想唤醒一个dialog，尝试调用他的show()方法

**Comment by min-team** [comment]
目前小程序提供的api能力有限，暂时没办法在page里直接搜索组件，暂时的过渡方案是将wxc-dialog 这类有显隐切换的组件，增加一个 properties 字段，控制组件的显示和隐藏。不过目前还没提供这类api，我们在考虑最佳方案，如果可行会尽快发布上线

**Comment by fisherwise** [comment]
cli提供了这个选项 但是实测没用 依旧报错 还是要打开ES6转ES5
