### ISSUE TITLE
我clone下来后

### ISSUE THREAD

**Issue by dusunboy** [meili/minui#17]
编译器报这个错Component is not found in path "pages/flex/@minui/wxc-example"
找不到这个组件，为啥

**Comment by min-team** [comment]
麻烦贴一下组件安装到的路径和 pages/ 目录之间的层级关系，以及组件引入的姿势？

**Comment by badeng** [comment]
可以把你的项目工程和目录结构等发出来吗，目前看像是路径错误

**Comment by dusunboy** [comment]
之前dist/packages目录下是没有@minui目录的
我今早删掉dist目录后，升级了min-cli，就有发现@minui目录了，然后就正常了
