### ISSUE TITLE
进入组件demo页面什么都没有？

### ISSUE THREAD

**Issue by huobaiyu** [meili/minui#18]
按照本地使用说明操作完成后，在微信开发工具运行小程序，点击任何组件页面都为空！

**Comment by badeng** [comment]
微信开发者工具的基础版本是多少？麻烦看一下，要1.6以上的

**Comment by huobaiyu** [comment]
我选1.6.0也是空白的；
1.6.4、1.6.6 有内容但是没有样式

**Comment by min-team** [comment]
@huobaiyu 开发者工具上有错误日志么，再提供下wxml 面板的节点树

**Comment by min-team** [comment]
@huobaiyu 初步排查后，有可能是因为组件里用的一些全局的样式，而这些全局的样式是放在MinUI组件库项目下的。诸如icon组件用到的iconfont、dialog用到的自定义动画样式都在放在全局里，存在这类问题是因为前期小程序还不支持将iconfont 和 自定义动画放在自定义组件里。目前MinUI组件会修复此类问题，如果你遇到不是这类问题，看看能否提供下示例代码哈，我们尽快排查解决

**Comment by huobaiyu** [comment]
我没有写任何代码，就是按照文档本地执行min dev 命令后运行dist 小程序发现的问题。

**Comment by min-team** [comment]
@huobaiyu 你的开发者工具是最新版的吗？

**Comment by huobaiyu** [comment]
是的

**Comment by min-team** [comment]
你这个问题比较特殊，实在找不到可能存在的问题了，方便加微信私聊吗

**Comment by huobaiyu** [comment]
可以

**Comment by min-team** [comment]
麻烦加一下群，谢谢
[image](https://s10.mogucdn.com//mlcdn/c45406/171127_33912geh7aeih110ah6hi9j56ejhf_752x974.jpg)

**Comment by min-team** [comment]
麻烦加一下群，谢谢！
[群二维码](https://s10.mogucdn.com//mlcdn/c45406/171127_33912geh7aeih110ah6hi9j56ejhf_752x974.jpg)

**Comment by min-team** [comment]
麻烦加一下群，谢谢！
[群二维码](https://s10.mogucdn.com//mlcdn/c45406/171127_33912geh7aeih110ah6hi9j56ejhf_752x974.jpg)

**Comment by huobaiyu** [comment]
已经加了，winder。

**Comment by zyx0908** [comment]
demo打包完成后 我也是运行不起来~尴尬了

**Comment by huobaiyu** [comment]
那就不是我一个人遇到这个问题了

**Comment by min-team** [comment]
@zyx0908 demo打包后运行起来了么

**Comment by zyx0908** [comment]
@min-team 没有   “VM82:2 未找到 app.json 中的定义的 pages "distpagesabnorindex" 对应的 WXML 文件”

**Comment by min-team** [comment]
@zyx0908 方便加一下微信群吗，反馈方便一点。
[群二维码](https://s10.mogucdn.com//mlcdn/c45406/171127_33912geh7aeih110ah6hi9j56ejhf_752x974.jpg)

**Comment by min-team** [comment]
@zyx0908 类似路径问题已在新版本修复，请更新到最新版本再试
