### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by Wuuuu** [meili/minui#2]
生成出来的文件路径都是.\\这种。不知道是怎么回事

**Comment by sonicsunsky** [comment]
生成的文件路径跟小程序项目要求的文件路径格式不同，有这种\\， \，还有dist\\ 这些多余的分隔符之类的

**Comment by min-team** [comment]
@Wuuuu @sonicsunsky  是 windows 系统吗？windows 系统下确实有已知路径生成问题，这个问题会在最近几天的新版中优化掉。建议先使用 mac 系统。

**Comment by min-team** [comment]
@Wuuuu @sonicsunsky 是windows系统吗，windows系统页面路径问题已修复，请更新 Min Cli 到1.0.2版本

**Comment by Wuuuu** [comment]
好的。
