### ISSUE TITLE
iconfont项目地址可以开源不？方便灵活更新。

### ISSUE THREAD

**Issue by Mustang-666** [meili/minui#21]
建议出个微信小程序格式的项目demo，现在引用方式对于刚刚上手微信小程序的来说分费解，不会使用minui

**Comment by min-team** [comment]
@Mustang-666  您可以基于 minui 的开源代码，自己任意修改 icon 组件里引用的 iconfont 的，不必拘泥于我们提供了什么就用什么。本身 minui 就是作为 min cli 的一个最佳实践开源给大家做展示用的，我们鼓励其他用户基于 minui 来二次开发更符合其自身团队业务的组件库。
