### ISSUE TITLE
wepy 里正确调用 this.selectComponent 的方法

### ISSUE THREAD

**Issue by zaxlct** [meili/minui#26]
使用 ` this.$wxpage.selectComponent()`
找了好久，才找到。
再次感谢 minui 团队，谢谢。
#13

**Comment by min-team** [comment]
是的。在wepy项目中，由于Page对象是wepy重新封装的，没有selectComponent方法，要调用该方法可以使用this.$wxpage.selectComponent()。
这是一个网友整理的在wepy项目中使用min的文档，[wepy-X-minui](https://github.com/jimmyrogue/wepy-X-minui)，可做参考。
本周我们会发布一个全新的、完整的文档，把这些都整理进去。
再次感谢您的反馈！

**Comment by zaxlct** [comment]
@min-team 谢谢，祝 minui 越来越好。

**Comment by shangdev** [comment]
@zaxlct 
兄弟，你是把this.$wxpage.selectComponent()写到onLoad里的吗？我用了之后直接报错：Uncaught (in promise) TypeError: this.$wxpage.selectComponent is not a function

**Comment by acegank** [comment]
@shangdev 老铁，怎么解决的

**Comment by twinklexp** [comment]
@shangdev @min-team  我无论何处使用this.$wxpage.selectComponent 都是 is not a function。我比较了我自己项目的this.$wxpage对象和 wepy-X-minui项目的this.$wxpage对象，里面的__proto__是不一样的

**Comment by jacena** [comment]
感谢，终于解决，
