### ISSUE TITLE
wxc-popup 里调用 wxc-mask 为什么点击wxc-mask的时候wxc-popup也会关闭?

### ISSUE THREAD

**Issue by sonicsunsky** [meili/minui#27]
wxc-popup 里调用 wxc-mask,

相关代码如下:

`<view class="mask mask__status--{{status}}">
    <view class="mask__bg" style="background: rgba({{backgroundColor}},{{opacity}});" bindtap="omMaskTap"></view>
    <view class="mask__content mask__content--{{cAlign}}" style="{{__positionStyle}}">
      <slot></slot>
    </view>
  </view>`

`<wxc-mask status="{{maskStatus}}"></wxc-mask>
  <view class="popup popup__status--{{status}} popup__content-align--{{align}} popup__status--{{status}}--animotion-{{animationMode}}" bindtap="hide">
    <slot></slot>
  </view>`

`<button bindtap="showPopup">居中，有动画</button>
  <wxc-popup class="J_Popup" animation-mode="center" align="center">
    <view class="popup__content">Hello World</view>
  </wxc-popup>`

`showPopup() {
      let popupComponent = this.selectComponent('.J_Popup');
      popupComponent && popupComponent.show();
    },
    hidePopup() {
      let popupComponent = this.selectComponent('.J_Popup');
      popupComponent && popupComponent.hide();
    }`

如这个示例里,  点击wxc-popup自身可以关闭当前弹窗，或者加一个关闭按钮绑定事件hidePopup也可以关闭弹窗，但是为什么点击蒙层的时候也可以关闭当前弹窗? 

因为关闭弹窗都是调用了wxc-popup里的hide函数，但是点击蒙层并没有对应的代码来响应wxc-popup里的hide函数，只是调用了onMaskTap函数来隐藏蒙层，弹窗还没有关闭，为什么蒙层隐藏后弹窗也会跟着关闭呢?

求助大神一个完美的解释，多谢啦

**Comment by tinpont** [comment]
点击事件是穿透的。[小程序事件](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxml/event.html)
