### ISSUE TITLE
用了组件没有任何的效果

### ISSUE THREAD

**Issue by shaoxiong789** [meili/minui#28]
用了组件没有任何的效果

**Comment by min-team** [comment]
@shaoxiong789 方便加微信群反馈一下问题吗？
[群二维码](https://s3.mogucdn.com/mlcdn/c45406/171218_26l3dkdecdh26eg638h9afa49l8kj_1080x1920.png)

**Comment by g1mi** [comment]
@min-team 求二维码 @shaoxiong789 对啊，你的问题是啥问题

**Comment by g1mi** [comment]
@min-team 希望能出个快速入门的小案例啊🤕

**Comment by cds803** [comment]
@g1mi 请到文档页面查看 Min 使用交流群的二维码 
https://meili.github.io/min/
