### ISSUE TITLE
是我安装错了吗？

### ISSUE THREAD

**Issue by zhongzhenzhi** [meili/minui#29]
我按流程下载了，微信小程序引用dist但是看不到有组件，只有一句话<text class="github__url">https://github.com/meili/minui</text>，请是什么情况？？

**Comment by min-team** [comment]
@zhongzhenzhi 可以加微信群反馈下问题吗？
[群二维码](https://s3.mogucdn.com/mlcdn/c45406/171218_26l3dkdecdh26eg638h9afa49l8kj_1080x1920.png)

**Comment by min-team** [comment]
@zhongzhenzhi 请问遇到的问题是否已解决了么

**Comment by zhongzhenzhi** [comment]
谢谢，等有空再解决

**Comment by cds803** [comment]
@zhongzhenzhi 使用文档请移步：https://meili.github.io/min/，或者请在文档的右上角扫微信群二维码进入  Min使用交流群，欢迎进群讨论

**Comment by cds803** [comment]
@zhongzhenzhi 使用文档请移步：https://meili.github.io/min/
或者请在文档的右上角扫微信群二维码进入 Min使用交流群，欢迎进群讨论
