### ISSUE TITLE
安装依赖 $ npm install是在当前minui目录下还是cmd默认的c盘路径下？

### ISSUE THREAD

**Issue by sonicsunsky** [meili/minui#3]
$ npm install指令执行的目录没有说清楚，是cmd默认c盘路径还是当前minui小程序项目目录之下?

**Comment by min-team** [comment]
@sonicsunsky 在已有的小程序里使用minui组件，请使用 min install <name> 指令来安装需要的组件，请在当前的小程序项目下执行该命令。
