### ISSUE TITLE
更新之后遇到的问题

### ISSUE THREAD

**Issue by zaxlct** [meili/minui#36]
`Property Observer Error @ packages/@minui/wxc-mask/dist/index#observer`
` Cannot read property 'zIndex' of undefined`

`Property Observer Error @ packages/@minui/wxc-popup/dist/index#observer`
`Cannot read property 'zIndex' of undefined`

**Comment by min-team** [comment]
嗯 这个问题这周会发布的 已经修改了

**Comment by zaxlct** [comment]
@min-team 方便给个微信群的二维码吗

**Comment by min-team** [comment]
[群二维码](https://s10.mogucdn.com/mlcdn/c45406/180108_888g0d26e23h9j8fc9e3bd7j3e85h_430x430.jpg_320x999.jpg) 我们在minui小程序的about页面上也提供了

**Comment by min-team** [comment]
minui组件库更新了，可以更新组件了

**Comment by cds803** [comment]
请添加群助手 wUf18018252882 好友或者扫码加好友，并与群助手对话发送验证码 10088 按照指引进群。

![Min小助手](https://user-images.githubusercontent.com/387163/34713096-10856bf6-f560-11e7-9278-2f6050e7748c.jpg)

**Comment by cds803** [comment]
@zaxlct 1.0.6版本已修复此问题，请更新组件到最新版本
- @minui/wxc-loading: 1.0.5 => 1.0.6
- @minui/wxc-mask: 1.0.5 => 1.0.6
- @minui/wxc-popup: 1.0.5 => 1.0.6
