### ISSUE TITLE
使用wxc-toast组件提示错误 Expect END descriptor with depth 1 but get another

### ISSUE THREAD

**Issue by sonicsunsky** [meili/minui#8]
使用wxc-toast组件提示错误:
Error:** Expect END descriptor with depth 1 but get another

根据调试发现可能是icon的问题,
```
<wxc-toast is-show="{{$toast.show}}" text="分享成功" icon="yes" icon-color="#ff5777"></wxc-toast>
<button bindtap="showToast">自定义 icon 颜色的 toast</button>
```

去掉icon属性后使用正常不会报错，一旦加上icon就会报错 Expect END descriptor with depth 1 but get another
```
<wxc-toast is-show="{{$toast.show}}" text="分享成功" icon-color="#ff5777"></wxc-toast>
<button bindtap="showToast">自定义 icon 颜色的 toast</button>
```

win10系统;
微信开发者工具最新版v1.01.1711020;

**Comment by sonicsunsky** [comment]
跟wx-icon组件有关，但是wx-icon在wx-toast使用的时侯已经正常导入

`{
    "component": true,
    "usingComponents": {
        "wxc-icon": "../wx-icon/wx-icon"
    }
}`

**Comment by sonicsunsky** [comment]
console.group("Mon Nov 13 2017 11:05:41 GMT+0800 (中国标准时间) 渲染层错误")
        console.error(`Error: Expect END descriptor with depth 1 but get another`)
      console.groupEnd()

**Comment by badeng** [comment]
可以检查一下toast组件中icon组件的引入路径吗？我看你描述的toast组件引icon组件的路径好像有点不对：{ "component": true, "usingComponents": { "wxc-icon": "../wx-icon/wx-icon" } }。一个正确的示例路径如下：[image](https://s10.mogucdn.com/mlcdn/c45406/171113_4h0bf43kd8ae38k6le0l6k7ekl70l_1640x802.png)

**Comment by sonicsunsky** [comment]
路径肯定是对的，因为路径不对的话错误提示就不是这个了，而是路径下找不到某个组件之类的错误提示,

例如这样:
WAService.js:3 jsEnginScriptError
Component is not found in path "wx-components/wx-toast/iconfont/iconfont"
Error: Component is not found in path "wx-components/wx-toast/iconfont/iconfont"

是连加载icon组件都加载不出来的，现在是能够加载出来，所以调用icon组件的路径是对的

应该是别的问题

**Comment by sonicsunsky** [comment]
**是wx-前缀导致的，是小程序框架的一个bug，根目录下不能有wx-前缀开头的文件夹，而且调用的组件名称也不能有wx-这种前缀**

**Comment by badeng** [comment]
你好，可以提供一下工程的详细目录结构吗，或者做一个简易的有问题的工程打个压缩包上传下，这样我们好还原场景，解决这个问题

**Comment by min-team** [comment]
@sonicsunsky 前缀不用wx-，是不是就没问题了
