### ISSUE TITLE
icon 组件为什么不提供 color 属性？

### ISSUE THREAD

**Issue by zaxlct** [meili/minui#9]
感觉这个也是挺常用的，不然的话还得手写 css。

**Comment by min-team** [comment]
@zaxlct 

我来回答你这个问题。

首先针对 MinUI 这个 UI 组件库里的开源组件，我们的答复是：现阶段不会为 icon 提供单独的 color 属性。

您可以通过层叠样式表（CSS），用 Web 标准化的方式为 icon 的文字设置颜色。如果您就是喜欢通过设置额外的标签属性，来实现文字颜色的赋值，也可以通过定制自己的 UI 组件来实现。毕竟 MinUI 是开源的，自主权在使用者手中。

------ 加个分割线，下面说点其他的，不关心的可忽略 ------

不同的团队会有其遵守的不同的原则，对我们团队而言，基于Web 标准化的共识、结构与变现相分离，是遵循的规则之二 —— 能用标准化的方式（CSS 代码）进行的样式赋值，就不应通过为解构增加额外属性来实现。

不给 `<icon>` 提供 color 属性的原因，同 Web 标准化不再推荐如下面这样为文字设置颜色的理念一样：

`<font color="red">This is some text!</font>`

当然，受限于小程序组件化的作用域限制，已经在组件内部定义过的默认初始样式，是不能被组件外部的样式覆盖的。针对这类还需定制化的样式，目前只能通过额外的属性传参来实现。这也是为什么我们即使遵循上述原则，依然会有个别组件提供了 `background-color` 的属性的原因 —— 冲突时，业务实现优先，是要遵循的另一条规则。

------ 再来个分割线 ------

不知上述文字是否能回答您的问题。如看后嗤之以鼻也可理解，道不同多说是蠢，如对内容所说有些不理解，可自行 google 回归 2004 - 2009 前端业界经历过的与这个问题相关的历次讨论，包含但不限于 web 标准化运动、结构与表现相分离、结构与行为相分离、表现与行为相分离等等。

**Comment by zaxlct** [comment]
我目前正在用 minui，首先非常感谢 minui 的无偿开源。

认真看了上面的回复，再次感谢，又学到了一些 Web 标准化理念。

祝 minui 越来越好！
@min-team
